//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYshariaCooperative.login {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="login.Ilogin")]
    public interface Ilogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ilogin/login_member", ReplyAction="http://tempuri.org/Ilogin/login_memberResponse")]
        int login_member(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ilogin/login_member", ReplyAction="http://tempuri.org/Ilogin/login_memberResponse")]
        System.Threading.Tasks.Task<int> login_memberAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ilogin/login_admin", ReplyAction="http://tempuri.org/Ilogin/login_adminResponse")]
        int login_admin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ilogin/login_admin", ReplyAction="http://tempuri.org/Ilogin/login_adminResponse")]
        System.Threading.Tasks.Task<int> login_adminAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IloginChannel : NYshariaCooperative.login.Ilogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IloginClient : System.ServiceModel.ClientBase<NYshariaCooperative.login.Ilogin>, NYshariaCooperative.login.Ilogin {
        
        public IloginClient() {
        }
        
        public IloginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IloginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IloginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IloginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int login_member(string username, string password) {
            return base.Channel.login_member(username, password);
        }
        
        public System.Threading.Tasks.Task<int> login_memberAsync(string username, string password) {
            return base.Channel.login_memberAsync(username, password);
        }
        
        public int login_admin(string username, string password) {
            return base.Channel.login_admin(username, password);
        }
        
        public System.Threading.Tasks.Task<int> login_adminAsync(string username, string password) {
            return base.Channel.login_adminAsync(username, password);
        }
    }
}
