//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYshariaCooperative.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Daftarmember", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSC")]
    [System.SerializableAttribute()]
    public partial class Daftarmember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GajiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoHPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfBirthField, value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gaji {
            get {
                return this.GajiField;
            }
            set {
                if ((object.ReferenceEquals(this.GajiField, value) != true)) {
                    this.GajiField = value;
                    this.RaisePropertyChanged("Gaji");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jk {
            get {
                return this.JkField;
            }
            set {
                if ((object.ReferenceEquals(this.JkField, value) != true)) {
                    this.JkField = value;
                    this.RaisePropertyChanged("Jk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nama {
            get {
                return this.NamaField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaField, value) != true)) {
                    this.NamaField = value;
                    this.RaisePropertyChanged("Nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoHP {
            get {
                return this.NoHPField;
            }
            set {
                if ((object.ReferenceEquals(this.NoHPField, value) != true)) {
                    this.NoHPField = value;
                    this.RaisePropertyChanged("NoHP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Work {
            get {
                return this.WorkField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkField, value) != true)) {
                    this.WorkField = value;
                    this.RaisePropertyChanged("Work");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PinjamDetails", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSC")]
    [System.SerializableAttribute()]
    public partial class PinjamDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AngsuranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GajiiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDmemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdpinjamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JangkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JumlahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamapinjamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Angsuran {
            get {
                return this.AngsuranField;
            }
            set {
                if ((object.ReferenceEquals(this.AngsuranField, value) != true)) {
                    this.AngsuranField = value;
                    this.RaisePropertyChanged("Angsuran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gajii {
            get {
                return this.GajiiField;
            }
            set {
                if ((object.ReferenceEquals(this.GajiiField, value) != true)) {
                    this.GajiiField = value;
                    this.RaisePropertyChanged("Gajii");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDmem {
            get {
                return this.IDmemField;
            }
            set {
                if ((object.ReferenceEquals(this.IDmemField, value) != true)) {
                    this.IDmemField = value;
                    this.RaisePropertyChanged("IDmem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idpinjam {
            get {
                return this.IdpinjamField;
            }
            set {
                if ((object.ReferenceEquals(this.IdpinjamField, value) != true)) {
                    this.IdpinjamField = value;
                    this.RaisePropertyChanged("Idpinjam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jangka {
            get {
                return this.JangkaField;
            }
            set {
                if ((object.ReferenceEquals(this.JangkaField, value) != true)) {
                    this.JangkaField = value;
                    this.RaisePropertyChanged("Jangka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jumlah {
            get {
                return this.JumlahField;
            }
            set {
                if ((object.ReferenceEquals(this.JumlahField, value) != true)) {
                    this.JumlahField = value;
                    this.RaisePropertyChanged("Jumlah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namapinjam {
            get {
                return this.NamapinjamField;
            }
            set {
                if ((object.ReferenceEquals(this.NamapinjamField, value) != true)) {
                    this.NamapinjamField = value;
                    this.RaisePropertyChanged("Namapinjam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWCFSharia")]
    public interface IWCFSharia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSharia/insertMember", ReplyAction="http://tempuri.org/IWCFSharia/insertMemberResponse")]
        int insertMember(NYshariaCooperative.ServiceReference1.Daftarmember daftar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSharia/insertMember", ReplyAction="http://tempuri.org/IWCFSharia/insertMemberResponse")]
        System.Threading.Tasks.Task<int> insertMemberAsync(NYshariaCooperative.ServiceReference1.Daftarmember daftar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSharia/updateMember", ReplyAction="http://tempuri.org/IWCFSharia/updateMemberResponse")]
        int updateMember(NYshariaCooperative.ServiceReference1.Daftarmember daftar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSharia/updateMember", ReplyAction="http://tempuri.org/IWCFSharia/updateMemberResponse")]
        System.Threading.Tasks.Task<int> updateMemberAsync(NYshariaCooperative.ServiceReference1.Daftarmember daftar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSharia/insertPinjam", ReplyAction="http://tempuri.org/IWCFSharia/insertPinjamResponse")]
        int insertPinjam(NYshariaCooperative.ServiceReference1.PinjamDetails daftar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSharia/insertPinjam", ReplyAction="http://tempuri.org/IWCFSharia/insertPinjamResponse")]
        System.Threading.Tasks.Task<int> insertPinjamAsync(NYshariaCooperative.ServiceReference1.PinjamDetails daftar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSharia/UpdatePinjam", ReplyAction="http://tempuri.org/IWCFSharia/UpdatePinjamResponse")]
        int UpdatePinjam(NYshariaCooperative.ServiceReference1.PinjamDetails daftar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSharia/UpdatePinjam", ReplyAction="http://tempuri.org/IWCFSharia/UpdatePinjamResponse")]
        System.Threading.Tasks.Task<int> UpdatePinjamAsync(NYshariaCooperative.ServiceReference1.PinjamDetails daftar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFShariaChannel : NYshariaCooperative.ServiceReference1.IWCFSharia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFShariaClient : System.ServiceModel.ClientBase<NYshariaCooperative.ServiceReference1.IWCFSharia>, NYshariaCooperative.ServiceReference1.IWCFSharia {
        
        public WCFShariaClient() {
        }
        
        public WCFShariaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFShariaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFShariaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFShariaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertMember(NYshariaCooperative.ServiceReference1.Daftarmember daftar) {
            return base.Channel.insertMember(daftar);
        }
        
        public System.Threading.Tasks.Task<int> insertMemberAsync(NYshariaCooperative.ServiceReference1.Daftarmember daftar) {
            return base.Channel.insertMemberAsync(daftar);
        }
        
        public int updateMember(NYshariaCooperative.ServiceReference1.Daftarmember daftar) {
            return base.Channel.updateMember(daftar);
        }
        
        public System.Threading.Tasks.Task<int> updateMemberAsync(NYshariaCooperative.ServiceReference1.Daftarmember daftar) {
            return base.Channel.updateMemberAsync(daftar);
        }
        
        public int insertPinjam(NYshariaCooperative.ServiceReference1.PinjamDetails daftar) {
            return base.Channel.insertPinjam(daftar);
        }
        
        public System.Threading.Tasks.Task<int> insertPinjamAsync(NYshariaCooperative.ServiceReference1.PinjamDetails daftar) {
            return base.Channel.insertPinjamAsync(daftar);
        }
        
        public int UpdatePinjam(NYshariaCooperative.ServiceReference1.PinjamDetails daftar) {
            return base.Channel.UpdatePinjam(daftar);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePinjamAsync(NYshariaCooperative.ServiceReference1.PinjamDetails daftar) {
            return base.Channel.UpdatePinjamAsync(daftar);
        }
    }
}
