//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYshariaCooperative.ServicePinjam {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataPinjam", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSC")]
    [System.SerializableAttribute()]
    public partial class DataPinjam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AngsuranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GajiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDAnggotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JangkaPinjamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JumlahPinjamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Angsuran {
            get {
                return this.AngsuranField;
            }
            set {
                if ((object.ReferenceEquals(this.AngsuranField, value) != true)) {
                    this.AngsuranField = value;
                    this.RaisePropertyChanged("Angsuran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gaji {
            get {
                return this.GajiField;
            }
            set {
                if ((object.ReferenceEquals(this.GajiField, value) != true)) {
                    this.GajiField = value;
                    this.RaisePropertyChanged("Gaji");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDAnggota {
            get {
                return this.IDAnggotaField;
            }
            set {
                if ((object.ReferenceEquals(this.IDAnggotaField, value) != true)) {
                    this.IDAnggotaField = value;
                    this.RaisePropertyChanged("IDAnggota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JangkaPinjam {
            get {
                return this.JangkaPinjamField;
            }
            set {
                if ((object.ReferenceEquals(this.JangkaPinjamField, value) != true)) {
                    this.JangkaPinjamField = value;
                    this.RaisePropertyChanged("JangkaPinjam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JumlahPinjam {
            get {
                return this.JumlahPinjamField;
            }
            set {
                if ((object.ReferenceEquals(this.JumlahPinjamField, value) != true)) {
                    this.JumlahPinjamField = value;
                    this.RaisePropertyChanged("JumlahPinjam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nama {
            get {
                return this.NamaField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaField, value) != true)) {
                    this.NamaField = value;
                    this.RaisePropertyChanged("Nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePinjam.IServicePinjam")]
    public interface IServicePinjam {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePinjam/datapinjam", ReplyAction="http://tempuri.org/IServicePinjam/datapinjamResponse")]
        int datapinjam(NYshariaCooperative.ServicePinjam.DataPinjam pinjam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePinjam/datapinjam", ReplyAction="http://tempuri.org/IServicePinjam/datapinjamResponse")]
        System.Threading.Tasks.Task<int> datapinjamAsync(NYshariaCooperative.ServicePinjam.DataPinjam pinjam);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePinjamChannel : NYshariaCooperative.ServicePinjam.IServicePinjam, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePinjamClient : System.ServiceModel.ClientBase<NYshariaCooperative.ServicePinjam.IServicePinjam>, NYshariaCooperative.ServicePinjam.IServicePinjam {
        
        public ServicePinjamClient() {
        }
        
        public ServicePinjamClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePinjamClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePinjamClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePinjamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int datapinjam(NYshariaCooperative.ServicePinjam.DataPinjam pinjam) {
            return base.Channel.datapinjam(pinjam);
        }
        
        public System.Threading.Tasks.Task<int> datapinjamAsync(NYshariaCooperative.ServicePinjam.DataPinjam pinjam) {
            return base.Channel.datapinjamAsync(pinjam);
        }
    }
}
